### ISSUE TITLE
Linebreaks not correctly parsed

### ISSUE THREAD

**Issue by j05u3** [robertodevs/zeplin-flutter-extended#10]
When the text has line breaks like this:
![image](https://user-images.githubusercontent.com/7897132/76715425-5741ab00-66fa-11ea-8ee2-03b9fc9787a7.png)

It generates code that doesnt compile:
![image](https://user-images.githubusercontent.com/7897132/76715512-b56e8e00-66fa-11ea-8b18-1f03c6684199.png)

**Comment by robertodevs** [comment]
The PR is approved. Thanks
