### ISSUE TITLE
LinearGradient doesnt take into account opacity

### ISSUE THREAD

**Issue by j05u3** [robertodevs/zeplin-flutter-extended#12]
This container: 
![image](https://user-images.githubusercontent.com/7897132/76722635-764c3700-6712-11ea-84bc-7a7cacfcc6c3.png)

generates the following code:

```
new Container(
  width: 128.71484375,
  height: 27.947265625,
  decoration: new BoxDecoration(
    		gradient: LinearGradient(colors: [
      Color(0xfff73672),
      Color(0xfffa3244) ],
    stops: [
        0,
				1
    ]
    )
  )
)
```

which doesn't apply opacity and looks like this:

![image](https://user-images.githubusercontent.com/7897132/76722656-911eab80-6712-11ea-9b5c-583ad4e55958.png)

**Comment by robertodevs** [comment]
PR is approved. Thanks
