### ISSUE TITLE
Boxshadow Offset vertical direction need to be negated for flutter

### ISSUE THREAD

**Issue by jascodes** [robertodevs/zeplin-flutter-extended#5]

**Comment by roberto198907** [comment]
Hi @jascodes 

Could you give me an example?

**Comment by jascodes** [comment]
Offset in the example should be `offset: Offset(0,8),` but it is `offset: Offset(0,-8),`. So to be clear Offset is fliped.

Thx

![Screenshot from 2019-08-14 07-20-22](https://user-images.githubusercontent.com/1231593/62989022-1338b000-be64-11e9-84b2-80ad6aed7ce0.png)

**Comment by roberto198907** [comment]
Let me check this because I tried to negate some screens I have but I see the shadow inverted.

**Comment by robertodevs** [comment]
I have checked this feature and this keeps working fine. Here is the screenshot. I will proceed to close this issue so if you have a specific error help me to open a new one and send me the detail. Thanks
![Screen Shot 2020-02-28 at 20 29 05](https://user-images.githubusercontent.com/48741699/75599302-3f66f780-5a69-11ea-927f-f53f37ebf69c.png)
