### ISSUE TITLE
Use fonts / colors from style guide

### ISSUE THREAD

**Issue by szotp** [robertodevs/zeplin-flutter-extended#7]
Would it be possible, when generating Text / Container/ etc. code, to use colors already defined in style guide? I don't want to insert hex colors everywhere in my UI code so I need to manually change them each time.

**Comment by roberto198907** [comment]
Yes, it is possible, I need to work on it. Stay tuned to a new release.

**Comment by robertodevs** [comment]
This feature has been added to the new version. The new version is just waiting to be approved. I will proceed to close this thread. Thanks for your suggestion. 
![Screen Shot 2020-02-28 at 20 25 37](https://user-images.githubusercontent.com/48741699/75599244-928c7a80-5a68-11ea-923f-ab73809b3481.png)
